version: "3.3"

services:
  # the python server being the backend
  intro-ws:
    build: server
    volumes:
      - ./public:/usr/src/app/public
      - ./intro.db:/usr/src/app/intro.db
    environment:
      - ADMIN_PWD=changeMe
      - LAST_API_KEY=REPLACEME
      - LAST_API_SECRET=REPLACEME
#      - DISABLE_ADDING
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.intro-back.rule=Host(`introguesserws.example.org`)"
      - "traefik.http.routers.intro-back.entrypoints=web,websecure"
      - "traefik.http.routers.intro-back.tls.certresolver=myhttpchallenge"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto = https"

    networks:
      - behind_traefik

  # a static file server because I could not be **** to write it in python
  static:
    image: "halverneus/static-file-server"
    container_name: "static-introguesser-fileserver"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.intro-fs.rule=Host(`introguesser.example.org`)"
      - "traefik.http.routers.intro-fs.entrypoints=web,websecure"
      - "traefik.http.routers.intro-fs.tls.certresolver=myhttpchallenge"
    networks:
      - behind_traefik
    volumes:
      - "./public/:/web:ro"

# with a traefik setup

networks:
  behind_traefik:
    external: true
